services:
  worker:
    image: subsquid/p2p-worker:1.0.0
    restart: unless-stopped
    command: p2p
    environment:
      # How many chunks are downloaded in paralel.
      # You can increase this number if you have a good internet connection.
      CONCURRENT_DOWNLOADS: 3
      # Timeout for downloading a single file.
      # Increase it if you have the "operation timed out" errors in the logs.
      S3_TIMEOUT: 60
      # The connection is dropped if no data has arrived for this time.
      S3_READ_TIMEOUT: 3
      # RPC node of the Arbitrum network
      RPC_URL: ${RPC_URL:-https://sepolia-rollup.arbitrum.io/rpc}
      # RPC node of the Ethereum network
      L1_RPC_URL: ${L1_RPC_URL:-https://rpc.sepolia.org}
      # You can set it to "info,subsquid_worker=debug" to get debug logs
      RUST_LOG: "info"

      # You probably shouldn't change the values below
      SCHEDULER_ID: 12D3KooWQER7HEpwsvqSzqzaiV36d3Bn6DZrnwEunnzS76pgZkMU
      LOGS_COLLECTOR_ID: 12D3KooWC3GvQVqnvPwWz23sTW8G8HVokMnox62A7mnL9wwaSujk
      P2P_LISTEN_ADDRS: /ip4/0.0.0.0/udp/${LISTEN_PORT:?}/quic-v1
      P2P_PUBLIC_ADDRS: ${PUBLIC_ADDR}
      BOOT_NODES: >
        12D3KooWSRvKpvNbsrGbLXGFZV7GYdcrYNh4W2nipwHHMYikzV58 /dns4/testnet.subsquid.io/udp/22445/quic-v1,
        12D3KooWQC9tPzj2ShLn39RFHS5SGbvbP2pEd7bJ61kSW2LwxGSB /dns4/testnet.subsquid.io/udp/22446/quic-v1
      NETWORK: tethys
      DATA_DIR: /app/data
      KEY_PATH: /app/key
      SENTRY_DSN: https://f97ffef7e96eb533d4c527ce62e4cfbf@o1149243.ingest.us.sentry.io/4507056936779776
    user: "${UID}:${GID}"
    volumes:
      - ${DATA_DIR:?}:/app/data
      - ${KEY_PATH:?}:/app/key:ro
    ports:
      - "${PROMETHEUS_PORT:-9090}:8000"
      - "${LISTEN_PORT:?}:${LISTEN_PORT:?}/udp"
    deploy:
      resources:
        limits:
          memory: 16G